requirements.txt: revert back to DRF 3.6.4
Version 3.7 was causing 500 server error with message:
Exception Type: AttributeError at /api/v1/feed
Exception Value: 'NoneType' object has no attribute 'sponsor'
in /api/v1/feed